#!/usr/bin/env python3
"""Bake CM5 face PNGs into a C header for the Pico C++ build.

Each source PNG becomes two flat arrays — luminance (RGB mean, matching the CM5
pipeline) and alpha (shape mask) — emitted as `const uint8_t` so they land in
the RP2350's memory-mapped flash. A FaceAsset (see face_asset.h) ties the set
together with its expression names and eye/mouth region boxes.

Usage:
    python pico/tools/convert_assets.py --src faces/main --name main \
        --out pico/protoface/assets/main.h --width 64 --height 32

`--width/--height` is the authored face size (half the canvas with mirror on).
`--name` becomes the C identifier (FACE_<name>) referenced from config.h.

Requires Pillow on the host (`pip install Pillow`). Not run on the device.
"""

import argparse
import json
import os

from PIL import Image


def _arrays(img, w, h):
    """Return (lum_list, alpha_list) for *img* resized (nearest) to w x h."""
    img = img.convert("RGBA").resize((w, h), Image.NEAREST)
    px = img.load()
    lum, alpha = [], []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            lum.append((r + g + b) // 3)
            alpha.append(a)
    return lum, alpha


def _mask_array(img, w, h):
    """Return a single 0..255 weight per pixel = luminance * alpha / 255.

    Works whether the mask is drawn white-on-transparent or white-on-black.
    """
    img = img.convert("RGBA").resize((w, h), Image.NEAREST)
    px = img.load()
    out = []
    for y in range(h):
        for x in range(w):
            r, g, b, a = px[x, y]
            out.append(((r + g + b) // 3) * a // 255)
    return out


def _emit_array(out, name, data):
    out.append("static const uint8_t %s[%d] = {" % (name, len(data)))
    line = "  "
    for i, v in enumerate(data):
        line += "%d," % v
        if len(line) >= 110:
            out.append(line)
            line = "  "
    if line.strip():
        out.append(line)
    out.append("};")


def _box(cfg, key, sx, sy):
    if key not in cfg:
        return "{0, 0, 0, -1}"  # w<0 = unset
    d = cfg[key]
    return "{%d, %d, %d, %d}" % (
        int(round(d["x"] * sx)), int(round(d["y"] * sy)),
        max(1, int(round(d["w"] * sx))), max(1, int(round(d["h"] * sy))),
    )


def convert(src, name, out_path, w, h):
    cfg = {}
    cfg_path = os.path.join(src, "config.json")
    if os.path.exists(cfg_path):
        with open(cfg_path) as f:
            cfg = json.load(f)

    pngs = sorted(f for f in os.listdir(src) if f.lower().endswith(".png"))
    expr_map = dict(cfg.get("expressions", {}))
    if not expr_map:
        for p in pngs:
            stem = os.path.splitext(p)[0].lower()
            if stem not in ("blink", "mouth_open"):
                expr_map[stem] = p

    # Source authoring size, for scaling region boxes.
    draw = cfg.get("draw_size")
    if draw and len(draw) == 2 and draw[0] and draw[1]:
        src_w, src_h = draw
    elif pngs:
        with Image.open(os.path.join(src, pngs[0])) as im:
            src_w, src_h = im.size
    else:
        src_w, src_h = w, h
    sx, sy = w / float(src_w), h / float(src_h)

    out = []
    out.append("// Generated by tools/convert_assets.py — do not edit by hand.")
    out.append("#pragma once")
    out.append('#include "../face_asset.h"')
    out.append("")

    expr_names = []
    expr_images = []
    for ename, fname in expr_map.items():
        path = os.path.join(src, fname)
        if not os.path.exists(path):
            continue
        with Image.open(path) as im:
            lum, alpha = _arrays(im, w, h)
        base = "%s_%s" % (name, ename)
        _emit_array(out, base + "_lum", lum)
        _emit_array(out, base + "_alpha", alpha)
        expr_names.append(ename)
        expr_images.append(base)
        out.append("")

    if not expr_images:
        raise SystemExit("no expression PNGs found in %s" % src)

    # Names array.
    out.append("static const char *const %s_names[] = {%s};" % (
        name, ", ".join('"%s"' % n for n in expr_names)))
    # FaceImage array.
    fi = ", ".join("{%s_lum, %s_alpha}" % (b, b) for b in expr_images)
    out.append("static const FaceImage %s_expr[] = {%s};" % (name, fi))
    out.append("")

    def special(fname):
        path = os.path.join(src, fname)
        if not os.path.exists(path):
            return None
        with Image.open(path) as im:
            lum, alpha = _arrays(im, w, h)
        base = "%s_%s" % (name, os.path.splitext(fname)[0])
        _emit_array(out, base + "_lum", lum)
        _emit_array(out, base + "_alpha", alpha)
        out.append("")
        return base

    blink_base = special(cfg.get("blink", "blink.png"))
    mouth_base = special("mouth_open.png")

    def bake_mask(fname, suffix):
        path = os.path.join(src, fname)
        if not os.path.exists(path):
            return None
        with Image.open(path) as im:
            data = _mask_array(im, w, h)
        arr = "%s_%s" % (name, suffix)
        _emit_array(out, arr, data)
        out.append("")
        return arr

    eye_mask = bake_mask("eye_mask.png", "eyemask")
    mouth_mask = bake_mask("mouth_mask.png", "mouthmask")

    has_blink = "true" if blink_base else "false"
    blink_img = "{%s_lum, %s_alpha}" % (blink_base, blink_base) if blink_base else "{0, 0}"
    has_mouth = "true" if mouth_base else "false"
    mouth_img = "{%s_lum, %s_alpha}" % (mouth_base, mouth_base) if mouth_base else "{0, 0}"

    out.append("static const FaceAsset FACE_%s = {" % name)
    out.append("  %d, %d," % (w, h))
    out.append("  %d, %s_names, %s_expr," % (len(expr_images), name, name))
    out.append("  %s, %s," % (has_blink, blink_img))
    out.append("  %s, %s," % (has_mouth, mouth_img))
    out.append("  %s," % _box(cfg, "eye_left", sx, sy))
    out.append("  %s," % _box(cfg, "eye_right", sx, sy))
    out.append("  %s," % _box(cfg, "mouth", sx, sy))
    out.append("  %s," % (eye_mask if eye_mask else "0"))
    out.append("  %s," % (mouth_mask if mouth_mask else "0"))
    out.append("};")
    out.append("")

    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w") as f:
        f.write("\n".join(out))
    print("Wrote %s (%d expressions, %dx%d)" % (out_path, len(expr_images), w, h))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", required=True)
    ap.add_argument("--name", required=True, help="C identifier, e.g. main -> FACE_main")
    ap.add_argument("--out", required=True, help="output .h path")
    ap.add_argument("--width", type=int, default=64)
    ap.add_argument("--height", type=int, default=32)
    args = ap.parse_args()
    convert(args.src, args.name, args.out, args.width, args.height)


if __name__ == "__main__":
    main()
